Business Dataset

In [ ]:
import pandas as pd

business = pd.read_json(
    "/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_business.json",
    lines=True
)

              business_id                      name  \
0  Pns2l4eNsfO8kk83dixA6A  Abby Rappoport, LAC, CMQ
1  mpf3x-BjTdTEA3yCZrAYPw             The UPS Store
2  tUFrWirKiKi_TAnsVWINQQ                    Target
3  MTSW4McQd7CbVtyjqoe9mw        St Honore Pastries
4  mWMc6_wTdE0EUBKIGXDVfA  Perkiomen Valley Brewery

                           address           city state postal_code  \
0           1616 Chapala St, Ste 2  Santa Barbara    CA       93101
1  87 Grasso Plaza Shopping Center         Affton    MO       63123
2             5255 E Broadway Blvd         Tucson    AZ       85711
3                      935 Race St   Philadelphia    PA       19107
4                    101 Walnut St     Green Lane    PA       18054

    latitude   longitude  stars  review_count  is_open  \
0  34.426679 -119.711197    5.0             7        0
1  38.551126  -90.335695    3.0            15        1
2  32.223236 -110.880452    3.5            22        0
3  39.955505  -75.155564    4.0            80        1
4  40.338183  -75.471659    4.5            13        1

                                          attributes  \
0                      {'ByAppointmentOnly': 'True'}
1             {'BusinessAcceptsCreditCards': 'True'}
2  {'BikeParking': 'True', 'BusinessAcceptsCredit...
3  {'RestaurantsDelivery': 'False', 'OutdoorSeati...
4  {'BusinessAcceptsCreditCards': 'True', 'Wheelc...

                                          categories  \
0  Doctors, Traditional Chinese Medicine, Naturop...
1  Shipping Centers, Local Services, Notaries, Ma...
2  Department Stores, Shopping, Fashion, Home & G...
3  Restaurants, Food, Bubble Tea, Coffee & Tea, B...
4                          Brewpubs, Breweries, Food

                                               hours
0                                               None
1  {'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ...
2  {'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ...
3  {'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...
4  {'Wednesday': '14:0-22:0', 'Thursday': '16:0-2...

In [5]:
business.columns

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'attributes', 'categories', 'hours'],
      dtype='object')

In [6]:
business.shape

(150346, 14)

In [7]:
business.head(3)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."

In [8]:
business.describe

<bound method NDFrame.describe of                    business_id                      name  \
0       Pns2l4eNsfO8kk83dixA6A  Abby Rappoport, LAC, CMQ
1       mpf3x-BjTdTEA3yCZrAYPw             The UPS Store
2       tUFrWirKiKi_TAnsVWINQQ                    Target
3       MTSW4McQd7CbVtyjqoe9mw        St Honore Pastries
4       mWMc6_wTdE0EUBKIGXDVfA  Perkiomen Valley Brewery
...                        ...                       ...
150341  IUQopTMmYQG-qRtBk-8QnA              Binh's Nails
150342  c8GjPIOTGVmIemT7j5_SyQ      Wild Birds Unlimited
150343  _QAMST-NrQobXduilWEqSw         Claire's Boutique
150344  mtGm22y5c2UHNXDFAjaPNw  Cyclery & Fitness Center
150345  jV_XOycEzSlTx-65W906pg                   Sic Ink

                                address           city state postal_code  \
0                1616 Chapala St, Ste 2  Santa Barbara    CA       93101
1       87 Grasso Plaza Shopping Center         Affton    MO       63123
2                  5255 E Broadway Blvd         Tucson    AZ       85711
3                           935 Race St   Philadelphia    PA       19107
4                         101 Walnut St     Green Lane    PA       18054
...                                 ...            ...   ...         ...
150341                3388 Gateway Blvd       Edmonton    AB     T6J 5H2
150342               2813 Bransford Ave      Nashville    TN       37204
150343           6020 E 82nd St, Ste 46   Indianapolis    IN       46250
150344                     2472 Troy Rd   Edwardsville    IL       62025
150345            238 Apollo Beach Blvd   Apollo beach    FL       33572

         latitude   longitude  stars  review_count  is_open  \
0       34.426679 -119.711197    5.0             7        0
1       38.551126  -90.335695    3.0            15        1
2       32.223236 -110.880452    3.5            22        0
3       39.955505  -75.155564    4.0            80        1
4       40.338183  -75.471659    4.5            13        1
...           ...         ...    ...           ...      ...
150341  53.468419 -113.492054    3.0            13        1
150342  36.115118  -86.766925    4.0             5        1
150343  39.908707  -86.065088    3.5             8        1
150344  38.782351  -89.950558    4.0            24        1
150345  27.771002  -82.394910    4.5             9        1

                                               attributes  \
0                           {'ByAppointmentOnly': 'True'}
1                  {'BusinessAcceptsCreditCards': 'True'}
2       {'BikeParking': 'True', 'BusinessAcceptsCredit...
3       {'RestaurantsDelivery': 'False', 'OutdoorSeati...
4       {'BusinessAcceptsCreditCards': 'True', 'Wheelc...
...                                                   ...
150341  {'ByAppointmentOnly': 'False', 'RestaurantsPri...
150342  {'BusinessAcceptsCreditCards': 'True', 'Restau...
150343  {'RestaurantsPriceRange2': '1', 'BusinessAccep...
150344  {'BusinessParking': '{'garage': False, 'street...
150345  {'WheelchairAccessible': 'True', 'BusinessAcce...

                                               categories  \
0       Doctors, Traditional Chinese Medicine, Naturop...
1       Shipping Centers, Local Services, Notaries, Ma...
2       Department Stores, Shopping, Fashion, Home & G...
3       Restaurants, Food, Bubble Tea, Coffee & Tea, B...
4                               Brewpubs, Breweries, Food
...                                                   ...
150341                         Nail Salons, Beauty & Spas
150342  Pets, Nurseries & Gardening, Pet Stores, Hobby...
150343  Shopping, Jewelry, Piercing, Toy Stores, Beaut...
150344  Fitness/Exercise Equipment, Eyewear & Optician...
150345  Beauty & Spas, Permanent Makeup, Piercing, Tattoo

                                                    hours
0                                                    None
1       {'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ...
2       {'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ...
3       {'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...
4       {'Wednesday': '14:0-22:0', 'Thursday': '16:0-2...
...                                                   ...
150341  {'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3...
150342  {'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3...
150343                                               None
150344  {'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ...
150345  {'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19...

[150346 rows x 14 columns]>

In [9]:
business.info

<bound method DataFrame.info of                    business_id                      name  \
0       Pns2l4eNsfO8kk83dixA6A  Abby Rappoport, LAC, CMQ
1       mpf3x-BjTdTEA3yCZrAYPw             The UPS Store
2       tUFrWirKiKi_TAnsVWINQQ                    Target
3       MTSW4McQd7CbVtyjqoe9mw        St Honore Pastries
4       mWMc6_wTdE0EUBKIGXDVfA  Perkiomen Valley Brewery
...                        ...                       ...
150341  IUQopTMmYQG-qRtBk-8QnA              Binh's Nails
150342  c8GjPIOTGVmIemT7j5_SyQ      Wild Birds Unlimited
150343  _QAMST-NrQobXduilWEqSw         Claire's Boutique
150344  mtGm22y5c2UHNXDFAjaPNw  Cyclery & Fitness Center
150345  jV_XOycEzSlTx-65W906pg                   Sic Ink

                                address           city state postal_code  \
0                1616 Chapala St, Ste 2  Santa Barbara    CA       93101
1       87 Grasso Plaza Shopping Center         Affton    MO       63123
2                  5255 E Broadway Blvd         Tucson    AZ       85711
3                           935 Race St   Philadelphia    PA       19107
4                         101 Walnut St     Green Lane    PA       18054
...                                 ...            ...   ...         ...
150341                3388 Gateway Blvd       Edmonton    AB     T6J 5H2
150342               2813 Bransford Ave      Nashville    TN       37204
150343           6020 E 82nd St, Ste 46   Indianapolis    IN       46250
150344                     2472 Troy Rd   Edwardsville    IL       62025
150345            238 Apollo Beach Blvd   Apollo beach    FL       33572

         latitude   longitude  stars  review_count  is_open  \
0       34.426679 -119.711197    5.0             7        0
1       38.551126  -90.335695    3.0            15        1
2       32.223236 -110.880452    3.5            22        0
3       39.955505  -75.155564    4.0            80        1
4       40.338183  -75.471659    4.5            13        1
...           ...         ...    ...           ...      ...
150341  53.468419 -113.492054    3.0            13        1
150342  36.115118  -86.766925    4.0             5        1
150343  39.908707  -86.065088    3.5             8        1
150344  38.782351  -89.950558    4.0            24        1
150345  27.771002  -82.394910    4.5             9        1

                                               attributes  \
0                           {'ByAppointmentOnly': 'True'}
1                  {'BusinessAcceptsCreditCards': 'True'}
2       {'BikeParking': 'True', 'BusinessAcceptsCredit...
3       {'RestaurantsDelivery': 'False', 'OutdoorSeati...
4       {'BusinessAcceptsCreditCards': 'True', 'Wheelc...
...                                                   ...
150341  {'ByAppointmentOnly': 'False', 'RestaurantsPri...
150342  {'BusinessAcceptsCreditCards': 'True', 'Restau...
150343  {'RestaurantsPriceRange2': '1', 'BusinessAccep...
150344  {'BusinessParking': '{'garage': False, 'street...
150345  {'WheelchairAccessible': 'True', 'BusinessAcce...

                                               categories  \
0       Doctors, Traditional Chinese Medicine, Naturop...
1       Shipping Centers, Local Services, Notaries, Ma...
2       Department Stores, Shopping, Fashion, Home & G...
3       Restaurants, Food, Bubble Tea, Coffee & Tea, B...
4                               Brewpubs, Breweries, Food
...                                                   ...
150341                         Nail Salons, Beauty & Spas
150342  Pets, Nurseries & Gardening, Pet Stores, Hobby...
150343  Shopping, Jewelry, Piercing, Toy Stores, Beaut...
150344  Fitness/Exercise Equipment, Eyewear & Optician...
150345  Beauty & Spas, Permanent Makeup, Piercing, Tattoo

                                                    hours
0                                                    None
1       {'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ...
2       {'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ...
3       {'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...
4       {'Wednesday': '14:0-22:0', 'Thursday': '16:0-2...
...                                                   ...
150341  {'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3...
150342  {'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3...
150343                                               None
150344  {'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ...
150345  {'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19...

[150346 rows x 14 columns]>

User Dataset

In [11]:
user = pd.read_json("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_user.json", lines = True)

In [ ]:
user.head(3)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18

In [13]:
user.columns

Index(['user_id', 'name', 'review_count', 'yelping_since', 'useful', 'funny',
       'cool', 'elite', 'friends', 'fans', 'average_stars', 'compliment_hot',
       'compliment_more', 'compliment_profile', 'compliment_cute',
       'compliment_list', 'compliment_note', 'compliment_plain',
       'compliment_cool', 'compliment_funny', 'compliment_writer',
       'compliment_photos'],
      dtype='object')