In [2]:
import pandas as pd

restaurants = pd.read_csv("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/data/processed/restaurants_clean.csv")

restaurants.head(3)

,business_id,name,city,state,postal_code,latitude,longitude,stars,review_count,categories,attributes,hours,is_open
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'RestaurantsDelivery': 'False', 'OutdoorSeati...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...",1
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'BusinessParking': 'None', 'BusinessAcceptsCr...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '...",1
2,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,Affton,MO,63123,38.565165,-90.321087,3.0,19,"Pubs, Restaurants, Italian, Bars, American (Tr...","{'Caters': 'True', 'Alcohol': ""u'full_bar'"", '...",Uknown,0

In [3]:
restaurants["categories"].str.split(",").explode().str.strip().value_counts()

categories
Restaurants                  52268
Food                         15472
Nightlife                     8723
Sandwiches                    8366
Bars                          8337
                             ...
Home Theatre Installation        1
Homeowner Association            1
Kids Hair Salons                 1
Calabrian                        1
Gemstones & Minerals             1
Name: count, Length: 728, dtype: int64

In [4]:
category_counts = (
    restaurants["categories"]
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)

category_counts[category_counts >= 100]

categories
Restaurants              52268
Food                     15472
Nightlife                 8723
Sandwiches                8366
Bars                      8337
                         ...
Falafel                    103
International Grocery      102
Tea Rooms                  102
Pretzels                   100
Flowers & Gifts            100
Name: count, Length: 135, dtype: int64

In [7]:
category_df = category_counts.reset_index()

category_df.columns = ["Category", "Count"]

category_df

                      Category  Count
0                  Restaurants  52268
1                         Food  15472
2                    Nightlife   8723
3                   Sandwiches   8366
4                         Bars   8337
..                         ...    ...
723  Home Theatre Installation      1
724      Homeowner Association      1
725           Kids Hair Salons      1
726                  Calabrian      1
727       Gemstones & Minerals      1

[728 rows x 2 columns]

In [8]:
category_df["Feature Type"] = ""
category_df["Standardized Value"] = ""
category_df["Keep"] = ""

In [9]:
category_df.head(2)

      Category  Count Feature Type Standardized Value Keep
0  Restaurants  52268
1         Food  15472

In [10]:
category_df["Notes"] = ""

In [11]:
category_df.to_csv(
    "/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/data/reference/category_mapping.csv",
    index=False
)